### ISSUE TITLE
UI Size  isssus

### ISSUE THREAD

**Issue by lbb1993** [commonsguy/cwac-presentation#17]
Hi,my android phone connect a 640*400 screen.Everything is very well except that when I use dp or sp with two different phones,the size of the views are different.And I used the PresentationService's buildPresoView method params inflater to inflate my views.How to match second screen ui between different phones? Thank you~

**Comment by commonsguy** [comment]
Different devices will handle external displays differently. 640x400 is a non-traditional resolution, so I will not be surprised if you encounter different results from different devices. That is the nature of Android's external display support and `Presentation`.

If you have evidence that the problem is caused by this library, and not by `Presentation`, feel free to [add the necessary information to this issue](https://github.com/commonsguy/cwac-presentation/blob/master/CONTRIBUTING.md#contributing-bug-reports), and I can reopen it.

**Comment by lbb1993** [comment]
> Different devices will handle external displays differently. 640x400 is a non-traditional resolution, so I will not be surprised if you encounter different results from different devices. That is the nature of Android's external display support and `Presentation`.
> 
> If you have evidence that the problem is caused by this library, and not by `Presentation`, feel free to [add the necessary information to this issue](https://github.com/commonsguy/cwac-presentation/blob/master/CONTRIBUTING.md#contributing-bug-reports), and I can reopen it.

Thank you for quick reply. It is not library's bug,thank you for reply again!
